name: PrivateWarps
version: 1.2.1
author: GudfareN
main: pro.homiecraft.pw.PrivateWarps
website: homiecraft.pro
description: PrivateWarps provides warps for each individual player.

commands:
    privatewarps:
        description: Prints information about the plugin!
    padmin:
        aliases: pa
        permission: PrivateWarps.admin
        description: Admin commands for PrivateWarps. Type /padmin to see the options
    pwarp:
        aliases: pw
        permission: PrivateWarps.warp
        description: Warps you to the specified warp if it exist!
    pswarp:
        aliases: psw
        permission: PrivateWarps.warp.other
        description: Warp to another players warp(If it is shared to you)
    psetwarp:
        aliases: pset
        permission: PrivateWarps.setwarp
        description: Sets a private warp
    pdelwarp:
        aliases: pdel
        permission: PrivateWarps.delwarp
        description: Deletes a warp that you specify!
    pwarps:
        aliases: plist
        permission: PrivateWarps.listwarps
        description: List all warps available for you!
    pshare:
        aliases: ps
        permission: PrivateWarps.share
        description: Allows you to share one of your warps to another player!